import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { PrimaryButton } from "@/components/accounting-ui";
import { startOAuthLogin } from "@/constants/oauth";
import { useAuth } from "@/hooks/use-auth";
import { categoryMeta, formatAmount, useAccounting } from "@/lib/accounting";
import { trpc } from "@/lib/trpc";

export default function AssistantScreen() {
  const router = useRouter(); const { user, loading } = useAuth(); const { state, accountBalances, balanceSheet, netIncome } = useAccounting(); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const ask = trpc.assistant.ask.useMutation();
  const snapshot = useMemo(() => ({ currency: state.currency, totalAssets: balanceSheet.totalAssets, totalLiabilities: balanceSheet.totalLiabilities, totalEquity: balanceSheet.totalEquity, netIncome, isBalanced: balanceSheet.isBalanced, accounts: state.accounts.map((account) => ({ name: account.name, category: categoryMeta[account.category].label, balance: accountBalances[account.id] ?? 0 })) }), [accountBalances, balanceSheet, netIncome, state.accounts, state.currency]);
  async function requestAnalysis() { try { const result = await ask.mutateAsync({ question, snapshot }); setAnswer(result.answer); } catch (error) { Alert.alert("تعذر تشغيل المساعد", error instanceof Error ? error.message : "تحقق من اتصالك ثم حاول مرة أخرى."); } }
  return <ScreenContainer className="px-4" edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={22} color="#154C79" /></Pressable><Text style={styles.title}>المساعد الذكي</Text></View>{loading ? <Text style={styles.loading}>جارٍ التحقق من الحساب...</Text> : !user ? <View style={styles.lockCard}><MaterialIcons name="lock-outline" size={32} color="#154C79" /><Text style={styles.lockTitle}>سجّل الدخول لاستخدام المساعد</Text><Text style={styles.lockDescription}>يحمي تسجيل الدخول طلبات التحليل التي ترسلها من بياناتك المحلية.</Text><PrimaryButton label="تسجيل الدخول" icon="login" onPress={() => void startOAuthLogin()} /></View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.summaryCard}><MaterialIcons name="auto-awesome" size={24} color="#7357C8" /><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>تحليل مبني على ملخصك الحالي</Text><Text style={styles.summaryText}>الأصول: {formatAmount(balanceSheet.totalAssets, state.currency)} · الميزانية {balanceSheet.isBalanced ? "متوازنة" : "قيد المراجعة"}</Text></View></View><TextInput value={question} onChangeText={setQuestion} placeholder="مثال: ما الذي يوضحه صافي الربح الحالي؟" placeholderTextColor="#98A5AE" multiline textAlign="right" style={styles.input} /><PrimaryButton label={ask.isPending ? "جارٍ التحليل..." : "اطلب تحليلاً"} icon="send" onPress={() => void requestAnalysis()} disabled={ask.isPending || question.trim().length < 3} />{answer ? <View style={styles.answerCard}><View style={styles.answerHeader}><MaterialIcons name="insights" size={19} color="#7357C8" /><Text style={styles.answerTitle}>تحليل المساعد</Text></View><Text style={styles.answerText}>{answer}</Text><Text style={styles.disclaimer}>ملاحظة: هذا شرح عام ولا يغني عن الاستشارة المحاسبية أو القانونية المتخصصة.</Text></View> : null}</ScrollView>}</ScreenContainer>;
}
const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 20, paddingTop: 10 }, back: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 14, borderWidth: 1, height: 44, justifyContent: "center", width: 44 }, title: { color: "#14212B", fontSize: 25, fontWeight: "800", writingDirection: "rtl" }, loading: { color: "#65737E", textAlign: "center", writingDirection: "rtl" }, lockCard: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 22, borderWidth: 1, gap: 12, padding: 22 }, lockTitle: { color: "#14212B", fontSize: 18, fontWeight: "800", textAlign: "center", writingDirection: "rtl" }, lockDescription: { color: "#65737E", fontSize: 13, lineHeight: 20, textAlign: "center", writingDirection: "rtl" }, content: { gap: 14, paddingBottom: 25 }, summaryCard: { alignItems: "flex-start", backgroundColor: "#F3F0FE", borderRadius: 18, flexDirection: "row-reverse", gap: 10, padding: 14 }, summaryCopy: { alignItems: "flex-end", flex: 1 }, summaryTitle: { color: "#5E48A6", fontSize: 14, fontWeight: "800", writingDirection: "rtl" }, summaryText: { color: "#706687", fontSize: 11, marginTop: 4, textAlign: "right", writingDirection: "rtl" }, input: { backgroundColor: "#FFFFFF", borderColor: "#D7E1E8", borderRadius: 18, borderWidth: 1, color: "#14212B", fontSize: 15, minHeight: 120, padding: 14, textAlignVertical: "top", writingDirection: "rtl" }, answerCard: { backgroundColor: "#FFFFFF", borderColor: "#DCD5F5", borderRadius: 20, borderWidth: 1, gap: 10, padding: 15 }, answerHeader: { alignItems: "center", flexDirection: "row-reverse", gap: 7 }, answerTitle: { color: "#5E48A6", fontSize: 15, fontWeight: "800", writingDirection: "rtl" }, answerText: { color: "#33454F", fontSize: 14, lineHeight: 23, textAlign: "right", writingDirection: "rtl" }, disclaimer: { color: "#8E839E", fontSize: 11, lineHeight: 17, textAlign: "right", writingDirection: "rtl" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
