import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { PrimaryButton } from "@/components/accounting-ui";
import { startOAuthLogin } from "@/constants/oauth";
import { useAuth } from "@/hooks/use-auth";

export default function ProfileScreen() {
  const router = useRouter(); const { user, loading, logout } = useAuth();
  async function signOut() { await logout(); Alert.alert("تم تسجيل الخروج", "تم إنهاء جلسة حسابك على هذا الجهاز."); }
  return <ScreenContainer className="px-4" edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={22} color="#154C79" /></Pressable><Text style={styles.title}>الحساب</Text></View>{loading ? <Text style={styles.loading}>جارٍ التحقق من حسابك...</Text> : user ? <View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{(user.name || "م").slice(0, 1)}</Text></View><Text style={styles.name}>{user.name || "مستخدم المحاسب الذكي"}</Text>{user.email ? <Text style={styles.email}>{user.email}</Text> : null}<View style={styles.secureRow}><MaterialIcons name="verified-user" size={19} color="#168A63" /><Text style={styles.secureText}>جلسة دخول محمية ومتصلة بحسابك</Text></View><Pressable onPress={() => void signOut()} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><Text style={styles.logoutText}>تسجيل الخروج</Text></Pressable></View> : <View style={styles.card}><View style={styles.avatar}><MaterialIcons name="lock-outline" size={30} color="#154C79" /></View><Text style={styles.name}>حسابك غير مسجل</Text><Text style={styles.description}>سجّل الدخول لحماية الوصول إلى المساعد الذكي وتفعيل المزايا المرتبطة بحسابك.</Text><PrimaryButton label="تسجيل الدخول" icon="login" onPress={() => void startOAuthLogin()} /></View>}</ScreenContainer>;
}
const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 24, paddingTop: 10 }, back: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 14, borderWidth: 1, height: 44, justifyContent: "center", width: 44 }, title: { color: "#14212B", fontSize: 25, fontWeight: "800", writingDirection: "rtl" }, loading: { color: "#65737E", fontSize: 14, textAlign: "center", writingDirection: "rtl" }, card: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 24, borderWidth: 1, gap: 11, padding: 22 }, avatar: { alignItems: "center", backgroundColor: "#DCEAF7", borderRadius: 32, height: 64, justifyContent: "center", width: 64 }, avatarText: { color: "#154C79", fontSize: 26, fontWeight: "800" }, name: { color: "#14212B", fontSize: 19, fontWeight: "800", textAlign: "center", writingDirection: "rtl" }, email: { color: "#65737E", fontSize: 13 }, description: { color: "#65737E", fontSize: 13, lineHeight: 21, textAlign: "center", writingDirection: "rtl" }, secureRow: { alignItems: "center", backgroundColor: "#E7F6EF", borderRadius: 13, flexDirection: "row-reverse", gap: 7, marginTop: 4, padding: 11, width: "100%" }, secureText: { color: "#168A63", flex: 1, fontSize: 12, fontWeight: "700", textAlign: "right", writingDirection: "rtl" }, logout: { alignItems: "center", borderColor: "#C44747", borderRadius: 14, borderWidth: 1, justifyContent: "center", marginTop: 5, minHeight: 47, width: "100%" }, logoutText: { color: "#C44747", fontSize: 14, fontWeight: "800", writingDirection: "rtl" }, pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
