import type { Account, Voucher } from "@/lib/accounting";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char] ?? char);
const printAmount = (amount: number, currency: string) => `${new Intl.NumberFormat("ar-LY", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount)} ${escapeHtml(currency)}`;

export function buildVoucherHtml({ voucher, accounts, currency }: { voucher: Voucher; accounts: Account[]; currency: string }) {
  const cash = accounts.find((account) => account.id === voucher.cashAccountId);
  const counterpart = accounts.find((account) => account.id === voucher.counterpartAccountId);
  const title = voucher.type === "receipt" ? "سند قبض" : "سند صرف";
  const movement = voucher.type === "receipt" ? "من ح/" : "إلى ح/";
  return `<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>@page{margin:22px}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#14212B;line-height:1.6}.sheet{border:1px solid #DDE5EB;border-radius:16px;padding:26px;max-width:760px;margin:auto}.top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #154C79;padding-bottom:16px}.brand{color:#154C79;font-size:22px;font-weight:700}.kind{display:inline-block;border-radius:999px;padding:6px 12px;background:${voucher.type === "receipt" ? "#E3F5EE" : "#FFF4DD"};color:#154C79;font-weight:700}.number{font-size:14px;color:#65737E}.amount{font-size:28px;font-weight:700;color:#154C79;margin:24px 0;text-align:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field{border:1px solid #E4EAEE;border-radius:10px;padding:10px 12px}.label{font-size:12px;color:#65737E}.value{font-weight:700}.note{margin-top:16px;background:#F6F9FB;border-radius:10px;padding:12px}.footer{margin-top:30px;padding-top:15px;border-top:1px solid #E4EAEE;font-size:12px;color:#65737E;display:flex;justify-content:space-between}</style></head><body><main class="sheet"><header class="top"><div><div class="brand">المحاسب الذكي</div><div class="number">${escapeHtml(voucher.voucherNumber)} · ${escapeHtml(voucher.date)}</div></div><div class="kind">${title}</div></header><div class="amount">${printAmount(voucher.amount, currency)}</div><section class="grid"><div class="field"><div class="label">اسم الجهة</div><div class="value">${escapeHtml(voucher.partyName)}</div></div><div class="field"><div class="label">طريقة الدفع</div><div class="value">${escapeHtml({ cash: "نقدي", cheque: "شيك", bank_transfer: "تحويل مصرفي", other: "أخرى" }[voucher.paymentMethod])}</div></div><div class="field"><div class="label">الحساب النقدي / البنكي</div><div class="value">${escapeHtml(cash ? `${cash.code} — ${cash.name}` : "غير متاح")}</div></div><div class="field"><div class="label">الحساب المقابل</div><div class="value">${escapeHtml(counterpart ? `${counterpart.code} — ${counterpart.name}` : "غير متاح")}</div></div></section><section class="note"><strong>${movement}</strong> ${escapeHtml(voucher.description)}</section><footer class="footer"><span>قيد داخلي متوازن مرتبط بالسند</span><span>تاريخ الإنشاء: ${new Date(voucher.createdAt).toLocaleDateString("ar-LY")}</span></footer></main></body></html>`;
}
