import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useEffect, useMemo, useState } from "react";
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState, PrimaryButton } from "@/components/accounting-ui";
import { currencyOptionsForBase, formatAmount, useAccounting } from "@/lib/accounting";

export default function AddEntryScreen() {
  const { state, addJournalEntry } = useAccounting();
  const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [debitAccountId, setDebitAccountId] = useState(""); const [creditAccountId, setCreditAccountId] = useState(""); const [documentReference, setDocumentReference] = useState(""); const [entryCurrency, setEntryCurrency] = useState(state.currency); const [fxRate, setFxRate] = useState(""); const [saving, setSaving] = useState(false);
  const documentCurrencies = useMemo(() => currencyOptionsForBase(state.currency, state.currencies), [state.currencies, state.currency]);
  useEffect(() => { setEntryCurrency(state.currency); }, [state.currency]);
  const debitAccount = useMemo(() => state.accounts.find((account) => account.id === debitAccountId), [debitAccountId, state.accounts]);
  const creditAccount = useMemo(() => state.accounts.find((account) => account.id === creditAccountId), [creditAccountId, state.accounts]);
  const numericAmount = Number(amount.replace(",", "."));
  const numericFxRate = Number(fxRate.replace(",", "."));
  const isBalanced = Boolean(debitAccount && creditAccount && debitAccount.id !== creditAccount.id && Number.isFinite(numericAmount) && numericAmount > 0 && entryCurrency.trim() && Number.isFinite(numericFxRate) && numericFxRate > 0);
  async function saveJournal() { try { setSaving(true); if (!isBalanced || !debitAccount || !creditAccount) throw new Error("اختر حسابين مختلفين، وأدخل مبلغاً وعملةً وسعر صرف صحيحين."); await addJournalEntry({ description, date: new Date().toISOString(), currency: entryCurrency, fxRate: numericFxRate, documentReference, lines: [{ accountId: debitAccount.id, category: debitAccount.category, debit: numericAmount, credit: 0 }, { accountId: creditAccount.id, category: creditAccount.category, debit: 0, credit: numericAmount }] }); setDescription(""); setAmount(""); setDebitAccountId(""); setCreditAccountId(""); setDocumentReference(""); setEntryCurrency(state.currency); setFxRate(""); Alert.alert("تم حفظ القيد", "القيد متوازن وتم تحديث الأرصدة والتقارير تلقائياً."); } catch (error) { Alert.alert("تعذر حفظ القيد", error instanceof Error ? error.message : "تحقق من البيانات المدخلة."); } finally { setSaving(false); } }
  if (!state.accounts.length) return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.emptyWrap}><EmptyState icon="account-tree" title="أنشئ حساباتك أولاً" description="أضف حسابين على الأقل من تبويب «الحسابات»، ثم أنشئ قيداً مديناً ودائناً متوازناً." /></View></ScreenContainer>;
  return <ScreenContainer className="px-4" containerClassName="bg-background"><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View style={styles.icon}><MaterialIcons name="balance" size={25} color="#154C79" /></View><View style={styles.headerCopy}><Text style={styles.eyebrow}>إدخال محاسبي</Text><Text style={styles.title}>قيد مزدوج</Text></View></View>
    <View style={styles.formCard}><Text style={styles.fieldLabel}>وصف القيد</Text><TextInput value={description} onChangeText={setDescription} placeholder="مثال: إيداع رأس مال نقدي" placeholderTextColor="#98A5AE" style={styles.input} textAlign="right" returnKeyType="next" />
      <Text style={styles.fieldLabel}>الحساب المدين</Text><AccountPicker accounts={state.accounts} selectedId={debitAccountId} onSelect={setDebitAccountId} color="#168A63" />
      <Text style={styles.fieldLabel}>الحساب الدائن</Text><AccountPicker accounts={state.accounts} selectedId={creditAccountId} onSelect={setCreditAccountId} color="#B97512" />
      <Text style={styles.fieldLabel}>مبلغ القيد بدفتر الأستاذ ({state.currency})</Text><TextInput value={amount} onChangeText={setAmount} placeholder="0.00" placeholderTextColor="#98A5AE" keyboardType="decimal-pad" style={styles.input} textAlign="right" />
      <Text style={styles.fieldLabel}>عملة المستند</Text><CurrencyPicker currencies={documentCurrencies} selectedCode={entryCurrency} onSelect={setEntryCurrency} />
      <Text style={styles.fieldLabel}>سعر الصرف</Text><TextInput value={fxRate} onChangeText={setFxRate} placeholder="أدخل سعر الصرف الذي تستخدمه" placeholderTextColor="#98A5AE" keyboardType="decimal-pad" style={styles.input} textAlign="right" />
      <Text style={styles.fieldLabel}>مرجع المستند (اختياري)</Text><TextInput value={documentReference} onChangeText={setDocumentReference} placeholder="رقم فاتورة أو سند أو مرجع داخلي" placeholderTextColor="#98A5AE" style={styles.input} textAlign="right" returnKeyType="done" />
      <Text style={styles.currencyHint}>تُسجل قيمة القيد بعملة دفتر الأستاذ أعلاه؛ العملة وسعر الصرف يوثقان المستند للمراجعة ولا يغيران التوازن. أضف أو احذف العملات من الإعدادات.</Text>
      <View style={[styles.balancePanel, isBalanced ? styles.balanced : styles.unbalanced]}><MaterialIcons name={isBalanced ? "verified" : "warning-amber"} size={20} color={isBalanced ? "#168A63" : "#B97512"} /><View style={styles.balanceCopy}><Text style={[styles.balanceTitle, { color: isBalanced ? "#168A63" : "#8A5A10" }]}>{isBalanced ? "القيد متوازن" : "بانتظار أطراف القيد"}</Text><Text style={styles.balanceHint}>{isBalanced ? `مدين ${formatAmount(numericAmount, state.currency)} = دائن ${formatAmount(numericAmount, state.currency)}` : "اختر حساباً مديناً وآخر دائناً بالمبلغ نفسه."}</Text></View></View>
      <PrimaryButton label={saving ? "جارٍ الحفظ..." : "حفظ القيد المتوازن"} icon="save" onPress={saveJournal} disabled={saving || !isBalanced} />
    </View>
  </ScrollView></KeyboardAvoidingView></ScreenContainer>;
}
function AccountPicker({ accounts, selectedId, onSelect, color }: { accounts: { id: string; name: string; category: string }[]; selectedId: string; onSelect: (id: string) => void; color: string }) { return <View style={styles.accountChips}>{accounts.map((account) => <Pressable key={account.id} onPress={() => onSelect(account.id)} style={[styles.accountChip, selectedId === account.id && { backgroundColor: color, borderColor: color }]}><Text style={[styles.accountChipText, selectedId === account.id && { color: "#FFFFFF" }]}>{account.name}</Text></Pressable>)}</View>; }
function CurrencyPicker({ currencies, selectedCode, onSelect }: { currencies: { code: string; name: string }[]; selectedCode: string; onSelect: (code: string) => void }) { return <FlatList horizontal showsHorizontalScrollIndicator={false} data={currencies} keyExtractor={(currency) => currency.code} contentContainerStyle={styles.currencyOptions} renderItem={({ item }) => <Pressable onPress={() => onSelect(item.code)} style={({ pressed }) => [styles.currencyOption, selectedCode === item.code && styles.currencyOptionSelected, pressed && styles.pressed]}><Text style={[styles.currencyOptionCode, selectedCode === item.code && styles.currencyOptionCodeSelected]}>{item.code}</Text><Text style={[styles.currencyOptionName, selectedCode === item.code && styles.currencyOptionNameSelected]}>{item.name}</Text></Pressable>} />; }
const styles = StyleSheet.create({ flex: { flex: 1 }, content: { gap: 18, paddingBottom: 28, paddingTop: 10 }, emptyWrap: { flex: 1, justifyContent: "center" }, header: { alignItems: "center", flexDirection: "row", gap: 12 }, icon: { alignItems: "center", backgroundColor: "#DCEAF7", borderRadius: 16, height: 46, justifyContent: "center", width: 46 }, headerCopy: { alignItems: "flex-end", flex: 1 }, eyebrow: { color: "#65737E", fontSize: 12, fontWeight: "600", writingDirection: "rtl" }, title: { color: "#14212B", fontSize: 26, fontWeight: "800", lineHeight: 35, writingDirection: "rtl" }, formCard: { backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 22, borderWidth: 1, gap: 10, padding: 16 }, fieldLabel: { color: "#33454F", fontSize: 13, fontWeight: "800", marginTop: 4, textAlign: "right", writingDirection: "rtl" }, input: { backgroundColor: "#F6F8FA", borderColor: "#E1E8EE", borderRadius: 14, borderWidth: 1, color: "#14212B", fontSize: 16, minHeight: 52, paddingHorizontal: 14, writingDirection: "rtl" }, currencyOptions: { gap: 8, paddingVertical: 2 }, currencyOption: { alignItems: "center", backgroundColor: "#F6F8FA", borderColor: "#E1E8EE", borderRadius: 14, borderWidth: 1, minHeight: 54, paddingHorizontal: 12, paddingVertical: 8 }, currencyOptionSelected: { backgroundColor: "#154C79", borderColor: "#154C79" }, currencyOptionCode: { color: "#154C79", fontSize: 14, fontWeight: "900" }, currencyOptionCodeSelected: { color: "#FFFFFF" }, currencyOptionName: { color: "#65737E", fontSize: 10, marginTop: 2, writingDirection: "rtl" }, currencyOptionNameSelected: { color: "#DCEAF7" }, currencyHint: { color: "#65737E", fontSize: 11, lineHeight: 18, textAlign: "right", writingDirection: "rtl" }, accountChips: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8 }, accountChip: { backgroundColor: "#F6F8FA", borderColor: "#E1E8EE", borderRadius: 16, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 9 }, accountChipText: { color: "#33454F", fontSize: 12, fontWeight: "700", writingDirection: "rtl" }, balancePanel: { alignItems: "center", borderRadius: 14, flexDirection: "row-reverse", gap: 9, marginTop: 4, padding: 13 }, balanced: { backgroundColor: "#E7F6EF" }, unbalanced: { backgroundColor: "#FFF4DD" }, balanceCopy: { alignItems: "flex-end", flex: 1 }, balanceTitle: { fontSize: 13, fontWeight: "800", writingDirection: "rtl" }, balanceHint: { color: "#65737E", fontSize: 11, marginTop: 3, textAlign: "right", writingDirection: "rtl" }, pressed: { opacity: 0.76 },
});
