import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { EmptyState } from "@/components/accounting-ui";
import { formatAmount, formatNumber, numberLocaleCode, useAccounting } from "@/lib/accounting";

export default function EntriesScreen() {
  const { state } = useAccounting();
  const accountsById = new Map(state.accounts.map((account) => [account.id, account]));
  return <ScreenContainer className="px-4" containerClassName="bg-background"><View style={styles.header}><Text style={styles.eyebrow}>دفتر اليومية</Text><Text style={styles.title}>القيود المزدوجة</Text></View><FlatList data={state.journalEntries} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={state.journalEntries.length ? styles.list : styles.emptyList} ListEmptyComponent={<EmptyState icon="receipt-long" title="لا توجد قيود مسجلة" description="أضف قيداً متوازناً ليظهر هنا طرفاه المدين والدائن." />} renderItem={({ item, index }) => <View style={styles.entryCard}><View style={styles.entryHeader}><View style={styles.verified}><MaterialIcons name="verified" size={16} color="#168A63" /><Text style={styles.verifiedText}>متوازن</Text></View><View style={styles.entryCopy}><Text style={styles.entryName}>{item.description}</Text><Text style={styles.entryDate}>قيد #{formatNumber(state.journalEntries.length - index)} · {new Intl.DateTimeFormat(numberLocaleCode(state.numberLocale), { dateStyle: "medium" }).format(new Date(item.date))}</Text></View></View><View style={styles.currencyMeta}><MaterialIcons name="currency-exchange" size={14} color="#154C79" /><Text style={styles.currencyMetaText}>مستند {item.currency ?? state.currency}{item.fxRate ? ` · سعر الصرف ${formatNumber(item.fxRate, { maximumFractionDigits: 6 })}` : " · لم يُسجل سعر صرف"}</Text></View>{item.lines.map((line) => { const account = accountsById.get(line.accountId); const isDebit = line.debit > 0; return <View key={line.id} style={styles.line}><View style={[styles.sideBadge, { backgroundColor: isDebit ? "#E3F5EE" : "#FFF4DD" }]}><Text style={[styles.sideText, { color: isDebit ? "#168A63" : "#B97512" }]}>{isDebit ? "مدين" : "دائن"}</Text></View><View style={styles.lineAccountWrap}><Text style={styles.lineAccount}>{account?.name ?? "حساب غير متاح"}</Text><Text style={styles.lineCode}>{account?.code ? `كود ${account.code}` : "بدون كود"}</Text></View><Text style={[styles.lineAmount, { color: isDebit ? "#168A63" : "#B97512" }]}>{formatAmount(isDebit ? line.debit : line.credit, state.currency)}</Text></View>; })}</View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ header: { alignItems: "flex-end", gap: 2, marginBottom: 15, paddingTop: 10 }, eyebrow: { color: "#65737E", fontSize: 12, fontWeight: "600", writingDirection: "rtl" }, title: { color: "#14212B", fontSize: 26, fontWeight: "800", lineHeight: 35, writingDirection: "rtl" }, list: { gap: 10, paddingBottom: 20 }, emptyList: { flexGrow: 1, justifyContent: "center", paddingBottom: 80 }, entryCard: { backgroundColor: "#FFFFFF", borderColor: "#E1E8EE", borderRadius: 18, borderWidth: 1, gap: 9, padding: 14 }, entryHeader: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, entryCopy: { alignItems: "flex-end", flex: 1 }, entryName: { color: "#14212B", fontSize: 16, fontWeight: "700", writingDirection: "rtl" }, entryDate: { color: "#98A5AE", fontSize: 11, marginTop: 3, writingDirection: "rtl" }, verified: { alignItems: "center", backgroundColor: "#E7F6EF", borderRadius: 12, flexDirection: "row-reverse", gap: 4, paddingHorizontal: 8, paddingVertical: 5 }, verifiedText: { color: "#168A63", fontSize: 11, fontWeight: "800", writingDirection: "rtl" }, currencyMeta: { alignSelf: "flex-end", alignItems: "center", backgroundColor: "#EAF3FA", borderRadius: 9, flexDirection: "row-reverse", gap: 5, paddingHorizontal: 8, paddingVertical: 5 }, currencyMetaText: { color: "#154C79", fontSize: 10, fontWeight: "700", writingDirection: "rtl" }, line: { alignItems: "center", backgroundColor: "#F8FAFB", borderRadius: 12, flexDirection: "row-reverse", gap: 8, minHeight: 46, paddingHorizontal: 9 }, sideBadge: { borderRadius: 8, paddingHorizontal: 7, paddingVertical: 4 }, sideText: { fontSize: 10, fontWeight: "800", writingDirection: "rtl" }, lineAccountWrap: { alignItems: "flex-end", flex: 1 }, lineAccount: { color: "#33454F", fontSize: 13, fontWeight: "700", textAlign: "right", writingDirection: "rtl" }, lineCode: { color: "#98A5AE", fontSize: 10, marginTop: 1, writingDirection: "ltr" }, lineAmount: { fontSize: 12, fontWeight: "800", writingDirection: "rtl" } });
